export enum ServiceOrderEventType {
  SERVICE_ORDER_CREATED = 'SERVICE_ORDER_CREATED',
  DIAGNOSIS_STARTED = 'DIAGNOSIS_STARTED',
  DIAGNOSIS_FINISHED = 'DIAGNOSIS_FINISHED',
  BUDGET_CREATED = 'BUDGET_CREATED',
  BUDGET_APPROVED = 'BUDGET_APPROVED',
  BUDGET_REJECTED = 'BUDGET_REJECTED',
  REPAIR_STARTED = 'REPAIR_STARTED',
  FINAL_TEST_STARTED = 'FINAL_TEST_STARTED',
  MAINTENANCE_FINISHED = 'MAINTENANCE_FINISHED',
  STATUS_UPDATED = 'STATUS_UPDATED'
}
