export enum ServiceOrderStatus {
  CREATED = 'CREATED',
  DIAGNOSIS_IN_PROGRESS = 'DIAGNOSIS_IN_PROGRESS',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  APPROVED = 'APPROVED',
  REPAIR_IN_PROGRESS = 'REPAIR_IN_PROGRESS',
  FINAL_TEST = 'FINAL_TEST',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}
