export enum ServiceOrderStatus {
  CREATED = 'CREATED',
  DIAGNOSIS_IN_PROGRESS = 'DIAGNOSIS_IN_PROGRESS',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  APPROVED = 'APPROVED',
  REPAIR_IN_PROGRESS = 'REPAIR_IN_PROGRESS',
  FINAL_TEST = 'FINAL_TEST',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum BudgetStatus {
  DRAFT = 'DRAFT',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED'
}

export enum ServiceOrderEventType {
  SERVICE_ORDER_CREATED = 'SERVICE_ORDER_CREATED',
  DIAGNOSIS_STARTED = 'DIAGNOSIS_STARTED',
  DIAGNOSIS_FINISHED = 'DIAGNOSIS_FINISHED',
  BUDGET_CREATED = 'BUDGET_CREATED',
  BUDGET_APPROVED = 'BUDGET_APPROVED',
  REPAIR_STARTED = 'REPAIR_STARTED',
  FINAL_TEST_STARTED = 'FINAL_TEST_STARTED',
  MAINTENANCE_FINISHED = 'MAINTENANCE_FINISHED'
}
